### ISSUE TITLE
Text Input Loose Focus when Warning Disappear

### ISSUE THREAD

**Issue by Tahinli** [elevenhsoft/WebApps#12]
Hi, It's not a bug absolutely but just quality of life improvement.
Can you keep focus on text input while writing. Because it looses focus when warnings disappear and user should click again to write. Definitely it's nothing but a little improvement.

https://github.com/elevenhsoft/WebApps/assets/96421894/26734c80-847b-4525-9d20-3e00e3673ae4

**Comment by elevenhsoft** [comment]
Oh yeah. It's already fixed with this commit: https://github.com/elevenhsoft/WebApps/commit/848bfc12521dd3adba7cee8c3279343022c8c50f
Just not on flathub yet. Today morning I made an update with latest changes to flathub but it's not yet available there. Just in few hours it should be updated i guess so it will be fixed. It's this bump: https://github.com/flathub/io.github.elevenhsoft.WebApps/commit/2ff3ccadac26c4805caa8252dddbffb00702e7d0

We need to wait a little bit :) Closing for not, btw. video is not working :P

**Comment by Tahinli** [comment]
> Oh yeah. It's already fixed with this commit: [848bfc1](https://github.com/elevenhsoft/WebApps/commit/848bfc12521dd3adba7cee8c3279343022c8c50f) Just not on flathub yet. Today morning I made an update with latest changes to flathub but it's not yet available there. Just in few hours it should be updated i guess so it will be fixed. It's this bump: [flathub/io.github.elevenhsoft.WebApps@2ff3cca](https://github.com/flathub/io.github.elevenhsoft.WebApps/commit/2ff3ccadac26c4805caa8252dddbffb00702e7d0)
> 
> We need to wait a little bit :) Closing for now.

Sorry, didn't know that.

**Comment by elevenhsoft** [comment]
Oh yeah! We are up-to-date on flathub: https://flathub.org/apps/io.github.elevenhsoft.WebApps

You can run update and check if it still persist.

**Comment by Tahinli** [comment]
> Oh yeah! We are up-to-date on flathub: https://flathub.org/apps/io.github.elevenhsoft.WebApps
> 
> You can run update and check if it still persist.

Solved!
