### ISSUE TITLE
No browser to select

### ISSUE THREAD

**Issue by j-urobles** [elevenhsoft/WebApps#18]
I am using the flatpak version of the app and it does not detect any browser when I have Firefox which is default in my distro.
![imagen](https://github.com/elevenhsoft/WebApps/assets/98100619/f10a9175-f8d3-4e4e-9543-c1fd878ae56f)
![imagen](https://github.com/elevenhsoft/WebApps/assets/98100619/4acee822-41f7-46e9-99b4-eb004817273e)

**Comment by elevenhsoft** [comment]
Hello!

Thank you for your report. Yeah. Probably this information is kind of miss leading, i will correct it.

The point is, flatpak version of this app works with flatpak browsers, since we don't have access to /usr/bin to checking what browser user have installed. Version installed via `just` (readme) is system-wide and works with both type of browsers. Sorry for confusion. I will correct this info.
