### ISSUE TITLE
(Question) Do you plan to use Servo?

### ISSUE THREAD

**Issue by hardBSDk** [elevenhsoft/WebApps#3]

**Comment by elevenhsoft** [comment]
Hey,
I did not think about this but it would be something huge.
If my skills will allow I will consider this later when app will be mostly done. Now there is a lot of changes and work in progress. Everything is constantly changing because I'm experimenting.
In the future we will see. The idea is nice. I like it :)

**Comment by boredsquirrel** [comment]
Once there is a working browser that uses the Servo engine this can be added, for now it is likely out of scope

**Comment by elevenhsoft** [comment]
I was thinking a bit about it. It can be done as a hard dependency to Web Apps. Let's say I would like to add this, since it would be nice a fallback for our apps. Unfortunately looks like servo needs specific toolchain to run, and since we (thanks to @mmstick) have a packaging for PopOS it would introduce some troubles. 

I need to dig this topic. Before we had something like `libsimpleservo` and now it's `servoshell`? Im not sure yet. If we will be stable and nothing new will be added, then in free time I can work with it to see how it will perform.

**Comment by mmstick** [comment]
Servo isn't ready for practical use yet. Outside of the demo pages on servo.org, most websites are completely broken. And they do not recommend using it to log into anything yet, supposing you can even get to a login.

**Comment by elevenhsoft** [comment]
Oh well. In that case it's waste of time to work on it. Yeah, i downloaded servo binary to run whatsapp web version and it did not work. Maybe we should just give up this idea for now.
