### ISSUE TITLE
[Bug] PNG Icons does not work

### ISSUE THREAD

**Issue by ZorinFoss** [elevenhsoft/WebApps#32]
Hi,

I can't choose png icon when add new url. Only svg icons works. what icon extensions is supported? and with what dimension `64x64` or `128x128 `. please add instruction about this.

Thanks,

**Comment by elevenhsoft** [comment]
Oh, i did not test png much. There is definitely some place to improvement, i'm gonna look into this. 
Icon selector looking for icons which are minimum 64x64 size, but it's concerns svg icons, so they are displayed.
When selecting via file picker, you should be able to choose whatever icon you want, because it depends on you if you want low quality icon or high, so there should not be much restriction. I'm gonna fix this soon, thank you :)

**Comment by elevenhsoft** [comment]
I think png should be fixed with last commit: https://github.com/elevenhsoft/WebApps/commit/696e885a1727da77ac81e944b873081da942247b
