### ISSUE TITLE
COSMIC File browser does not function for selecting icons from alternative location.

### ISSUE THREAD

**Issue by PGQT** [elevenhsoft/WebApps#41]
open 'cosmic web apps'
click 'create new web app'
click 'icon selector'
click 'open'

expected: file browser opens and allows navigation to desired folder/file for new app icon. 
experienced: file browser opens and is empty, but says 'Empty Folder (has hidden items)'. No content is displayed, but buttons seem to be 'clickable', while not really doing anything. 
![screenshot-2024-05-31-23-32-10](https://github.com/elevenhsoft/WebApps/assets/85464621/d396c998-b37d-402b-b425-6ac5e0b7432e)

**Comment by elevenhsoft** [comment]
Hmm, you probably have installed it as flatpak. Since flatpak is sandboxed and we don't have permissions to whole home location, it shows empty home folder. We are using cosmic-files for file picker and it's kind of "early" phase of development. I will implement file picker via portal so in case using different desktop, you will have native file picker. Maybe it will be less confusing. 

It's technically not a bug, but maybe less friendly UX.

If you would like to do some tests if it works. You can make a new folder in your home, put an icon there, give a COSMIC Web Apps permissions to this folder, maybe via Flatseal and it should be shown.

**Comment by elevenhsoft** [comment]
I just implemented xdg desktop portal file picker, so you will have native file picker for your desktop instead of hard coded cosmic-files: https://github.com/elevenhsoft/WebApps/commit/e2c0543d74026166b1aa89bc4e41f8f1b6a76776

which should works more familiar
