### ISSUE TITLE
Feature request: copy url

### ISSUE THREAD

**Issue by curiousercreative** [elevenhsoft/WebApps#49]
I'm previously using Chromium for PWA style web app windows. See screenshots for the top bar and the menu which crucially includes a copy url option. I also find myself using the refresh and back navigation buttons a bit.
![image](https://github.com/elevenhsoft/WebApps/assets/1696898/ac4b27fd-a312-4e46-9778-f1df1af668c0)
![image](https://github.com/elevenhsoft/WebApps/assets/1696898/e58f0d04-4120-49a9-a2ce-df407a4cbe19)

**Comment by elevenhsoft** [comment]
Yeah, I'm worry we can't do much with it. What we does is to open browser with specific URL and tell it to hide some stuff. To be honest, we can't control in easy way the browser's interface.

I was thinking about adding servo or webkit engines to this app but it will require a lot of work and not easy task. In this case we could control this behavior in more ways. Right now I'm closing this issue because I think I won't be able to do this.
