### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Tahinli** [elevenhsoft/WebApps#9]
Hi, I have been waiting for flathub release. Thanks a lot, I installed and it works now. 

I would like to contribute via translation into my main language Turkish. How can I offer this to you ?

**Comment by elevenhsoft** [comment]
Im glad it works for you! Waiting for your issues, haha :)

About translations. I will work on it in next few days. I will prepare template and starting translate it English -> Polish so people will be able to follow it and make PR.

When it will be ready I will ping u here, and we can work together. Now need to do some stuff related to flathub, their quality guidelines etc.

Since we are "stable" (im scared to say that word haha) we can do some minor things and improve this app.

**Comment by elevenhsoft** [comment]
Hey @Tahinli,
Just added localize system with fluent to our app. If you are still interested with contribution, feel free :)

Commit: https://github.com/elevenhsoft/WebApps/commit/cb6f67192708bc3413630a5bb54d6eca03b0a5ac

**Comment by Tahinli** [comment]
> Hey @Tahinli, Just added localize system with fluent to our app. If you are still interested with contribution, feel free :)
> 
> Commit: [cb6f671](https://github.com/elevenhsoft/WebApps/commit/cb6f67192708bc3413630a5bb54d6eca03b0a5ac)

Yeah, sure. I'm going to look at what I can do.
